version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACK_API_URL=${BACK_API_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
