version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - BACK_API_URL=${BACK_API_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always      
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ${DOCKER_COMPOSE_ROOT}/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - ${DOCKER_COMPOSE_ROOT}/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app